### ISSUE TITLE
Add tput to dependency list

### ISSUE THREAD

**Issue by sharan-aithal** [Bhupesh-V/ugit#1]
At first thanks for bringing such an undoing tool entirely in Bash.

#### What is the problem?
tput is maybe missing in some other os. I think it is better to add it in dependency list of ugit.

I would like to contribute if I have any new feature to add it here.😍

**Comment by sharan-aithal** [comment]
Can I open PR here

**Comment by Bhupesh-V** [comment]
This seems like a good idea. We would need to update it in 2 places
1. The README ofc
2. the `deps` array here:
    https://github.com/Bhupesh-V/ugit/blob/99edc9a6d32e7ee8add7bad97a5b9c8b6f53cdec/ugit#L24-L27

Thanks for reporting this 👍🏽
