### ISSUE TITLE
I'd like to add an oh-my-zsh-compatible plugin file

### ISSUE THREAD

**Issue by unixorn** [Bhupesh-V/ugit#10]
I'd like to add an oh-my-zsh compatible plugin file. This will let users of oh-my-zsh compatible shell frameworks automatically add ugit to their shell setup, and with some frameworks, automatically keep it up to date by periodically running `git pull`.

**Describe the solution you'd like**

Basically I'm going to write a very short (~3 lines of code) plugin file that the frameworks can load to automatically add the ugit repository to the user's `$PATH`.

**Comment by Bhupesh-V** [comment]
This seems like a good idea. Please do this 👍🏽 
Also, when you submit the PR, please add the Installation instructions in README for OMZ users

**Comment by unixorn** [comment]
Will do
