### ISSUE TITLE
Videos don't work in Firefox

### ISSUE THREAD

**Issue by TabulateJarl8** [Bhupesh-V/ugit#18]
I'm not sure if you can do anything about this, or if it's the fault of GitHub or something else, but I'll post an issue anyway.

**Describe the bug**
The videos in the README and on your blog post don't seem to be working in Firefox

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
<details><summary>README</summary>

![image](https://user-images.githubusercontent.com/58576759/120899184-69a84d00-c5fc-11eb-9046-65feb71758d6.png)

</details>

<details><summary>Blog</summary>

![image](https://user-images.githubusercontent.com/58576759/120899196-74fb7880-c5fc-11eb-8f35-f9960e6517a4.png)

</details>

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser: Firefox 89.0

**Additional context**
It seems to work in Chromium 90.0.4430.212 and Microsoft Edge 92.0.891.1

**Comment by Bhupesh-V** [comment]
Ah yes, thanks for reporting this. I have been ignoring this for a while now 😅 
Although a [user on lobster](https://lobste.rs/s/64lthd/undo_your_last_git_mistake_with_ugit) really dug into this

Seems like the encoding is not supported by FF. I don't want to use asciinema, since that's an additional 3rd party resource.
Will see what can be done with ffmpeg. Suggestions welcome

**Comment by TabulateJarl8** [comment]
I might try this on my own later, but I'm pretty sure H.264 encoding is supported by most browsers. This can be done pretty easily with ffmpeg using

```
ffmpeg -i input.whatever -c:v libx264 -preset slow -crf 20 -c:a aac -b:a 160k -vf format=yuv420p -movflags +faststart output.mp4
```

It might take a while to finish, and if the output quality is too low, try changing the number after `-crf` to be lower, as lower is higher quality (default is 23). I'll reply again if I do find that this is the solution

**Comment by TabulateJarl8** [comment]
Update: That does seem to fix the issue

**Comment by Bhupesh-V** [comment]
> I might try this on my own later, but I'm pretty sure H.264 encoding is supported by most browsers. This can be done pretty easily with ffmpeg using
> 
> ```
> ffmpeg -i input.whatever -c:v libx264 -preset slow -crf 20 -c:a aac -b:a 160k -vf format=yuv420p -movflags +faststart output.mp4
> ```
> 
> It might take a while to finish, and if the output quality is too low, try changing the number after `-crf` to be lower, as lower is higher quality (default is 23). I'll reply again if I do find that this is the solution

Thanks a lot for this 🙌🏽
Updated the demos in the readme
