### ISSUE TITLE
undoing `git rm`

### ISSUE THREAD

**Issue by Bhupesh-V** [Bhupesh-V/ugit#28]
**Is your feature request related to a problem? Please describe.**
Support for undoing `git rm` doesn't exist yet.

**Describe the solution you'd like**
this is straightforward, ref the following links:
- https://stackoverflow.com/questions/2125710/how-to-revert-a-git-rm-r

**Additional context**
- Make sure to list & handle out any edge cases
- Handle error states

**Comment by nalin-singh** [comment]
I would like to work on this for SSOC

**Comment by Bhupesh-V** [comment]
> I would like to work on this for SSOC

Sure go ahead, LMK if you need any help
