### ISSUE TITLE
Empty commit list when running `git fsck`

### ISSUE THREAD

**Issue by Bhupesh-V** [Bhupesh-V/ugit#29]
**Describe the bug**
The command `git fsck` will return no data if there are no unreachable commits in history. 

![wat](https://user-images.githubusercontent.com/34342551/165538247-36893827-f301-42ef-8a5e-6e0e1e325722.png)

**To Reproduce**
- Create a new git repo
- Stash something
- Run ugit and try to undo `git stash pop`

**Expected behavior**
ugit should exit if there is no data provided by `git fsck`

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Bash Version [5.0.17]
 - FZF Version: [0.27.2]
 - Git Version: [2.35.1]

**Additional context**
Check for this case while recovering deleted tag as well

**Comment by 2005493** [comment]
can I work on this issue??

**Comment by Bhupesh-V** [comment]
> can I work on this issue??

Hey do you have any update on this? Did you face any roadblocks?

**Comment by 2005493** [comment]
Sorry for the late reply.. ..i am currently working on this issue and If i
face some issue i will definitely let you know

**Comment by nalin-singh** [comment]
Hello @Bhupesh-V, I have worked on a solution for this. Could you assign this to me, I don't have permission to push right now.
Also I have sent a recording to you on discord.

**Comment by Bhupesh-V** [comment]
> Hello @Bhupesh-V, I have worked on a solution for this. Could you assign this to me, I don't have permission to push right now. Also I have sent a recording to you on discord.

Hey, thanks for taking the initiative, I have assigned you the issue.
Please for the project, and push your changes to a new branch. Then create a PR from that branch to ugit.
LMK if you face any issues.

PS: I checked the demo on discord, great work 🙌🏽

**Comment by nalin-singh** [comment]
I have added the PR #61, please have a look.
