### ISSUE TITLE
undoing `git tag`

### ISSUE THREAD

**Issue by Bhupesh-V** [Bhupesh-V/ugit#38]
### Is your feature request related to a problem? Please describe.

Let's say you accidentally create a git tag, feature to rename a git tag would be nice

**Comment by chakravartyk** [comment]
Hey @Bhupesh-V I'd like to work on this for SSOC

**Comment by Bhupesh-V** [comment]
> Hey @Bhupesh-V I'd like to work on this for SSOC

Sure, LMK if you need any help

**Comment by kopalchakravarty** [comment]
> Hey @Bhupesh-V I'd like to work on this for SSOC

Could you please assign the issue to this id instead? Thanks.
