### ISSUE TITLE
Fix empty/null condition edge-cases across ugit

### ISSUE THREAD

**Issue by Bhupesh-V** [Bhupesh-V/ugit#44]
I have overlooked handling edge-cases in multiple places, they need to be fixed for a more robut and error prone ugit.
1. handle no commit situation when undoing `git commit`, do not open the FZF menu.
2. return custom string when tags are not present while undoing `git tag`, again dont invoke FZF

Keeping this open to add more missed edge-cases as I discover. If you are looking to contribute please create separate PRs for each item listed above

**Comment by nalin-singh** [comment]
I would like to work on these issues @Bhupesh-V

**Comment by Bhupesh-V** [comment]
> I would like to work on these issues @Bhupesh-V

Sure, please go through the codebase to find any other edge cases as well
