### ISSUE TITLE
`--pointer=ᐅ` option not supported by older versions of fzf

### ISSUE THREAD

**Issue by tiojoca** [Bhupesh-V/ugit#6]
**Describe the bug**
For older versions of `fzf`, `ugit` returns the following error when executed:
```
Undo your last oopsie in Git 🙈️
unknown option: --pointer=ᐅ
```

I'm not sure in which version this option was added to fzf but I've tested with version 0.17.3.

**To Reproduce**
Install an older version `fzf` (eg. v0.17.3) and run `ugit` with no parameters.

**Expected behavior**
`ugit` should ignore the `fzf` error or the oldest functioning version of `fzf` should be added to the list of dependencies.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS 11.3
 - Bash Version: fish 3.2.1
 - FZF Version: 0.17.3

**Additional context**
N/A

**Comment by Bhupesh-V** [comment]
Thanks a lot for reporting this 👍🏽 

the `--pointer` option was added in [**0.21.0**](https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0210)

I think we should notify this in README, To install the most latest stable version of FZF.
Want to give it a shot?
