### ISSUE TITLE
Sort tags in proper order in "Undo git tag"

### ISSUE THREAD

**Issue by wrecklass** [Bhupesh-V/ugit#64]
### Is your feature request related to a problem? Please describe.

The current ugit method to undo_git_tag() calls `git tag`. This presents the tags in a string sort order that looks incorrectly sorted with numeric tags. For instance:

v1.0
v1.1
v1.10
v1.11
v1.2
v1.3
v1.4

etc.

### Describe the solution you'd like

Use `git tag --sort=v:refname` to present tags in correct order:

v1.0
v1.2
v1.3
v1.4
v1.10
v1.11

etc.

### Describe alternatives you've considered

You could create your own sorting method, but why?

**Comment by Bhupesh-V** [comment]
@wrecklass that's a nice find, thanks for reporting
LMK if you want to take this up

**Comment by wrecklass** [comment]
Sure, I can do a PR.
